name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: "3.14"
      - name: Set project version
        run: |
          TAG_VERSION="${{ github.ref_name }}"
          uv version "${TAG_VERSION#v}"
      - name: Build package
        run: uv build
      - name: Publish package distributions to PyPI
        run: uv publish --token ${{ secrets.PYPI_TOKEN }}
